apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roast-dinner.fullname" . }}-app
  labels:
    {{- include "roast-dinner.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ include "roast-dinner.secretKey" . | quote }}
