{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roast-dinner.serviceAccountName" . }}
  labels:
    {{- include "roast-dinner.labels" . | nindent 4 }}
{{- end }}
